### PR TITLE
Alphabetically sort the  var.js

### LINKED ISSUE #14: Alphabetically sort the vars.js file
Just a quick bit of alphabetical sorting is needed so that it is easier to add or change the variables.

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes #14

### CODE REVIEW

**Review by bsoyka — APPROVED** [review]
Looks great!

**Comment by bsoyka** [comment]
Thank you so much for helping out, @sowmiyamuthuraman!

**Comment by bsoyka** [comment]
@sowmiyamuthuraman - I've added you as a member of the `mystery-egg` GitHub organization, so that if you ever want to help out in the future, you can just make a new branch. :)

**Comment by sowmiyamuthuraman** [comment]
sure, Thanks!

**Pull request merged**
